// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            2
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:   6

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    caller
    (
        init => init
        upgrade => upgrade
        x => x
        caller_iteration_event => caller_iteration_event
        iterate_on_callers => iterate_on_callers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
