// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            2
// Async Callback (empty):               1
// Total number of exported functions:   5

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    callee
    (
        init => init
        upgrade => upgrade
        iterate_on_callees => iterate_on_callees
        callee_iteration_event => callee_iteration_event
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
